# Generated by Django 4.2.5 on 2023-12-28 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toys', to=settings.AUTH_USER_MODEL),
        ),
    ]
